#' Weighted glmnet prediction models modified from wlasso
#'
#'@description This function allows as to fit glmnet prediction (linear or logistic) models to complex survey data, considering sampling weights in the estimation process and selects the lambda that minimizes the error based on different replicating weights methods. When alpha = 1 (the default setting), produces same result as wlasso::wlasso()
#'
#' @param data A data frame with information about the response variable and covariates, as well as sampling weights and strata and cluster indicators. It could be \code{NULL} if the sampling design is indicated in the \code{design} argument.
#' @param col.y A numeric value indicating the number of the column in which information on the response variable can be found or a character string indicating the name of that column.
#' @param col.x A numeric vector indicating the numbers of the columns in which information on the covariates can be found or a vector of character strings indicating the names of these columns.
#' @param alpha A number or numeric vector indicating values of alpha
#' @param cluster A character string indicating the name of the column with cluster identifiers. It could be \code{NULL} if the sampling design is indicated in the \code{design} argument.
#' @param strata A character string indicating the name of the column with strata identifiers. It could be \code{NULL} if the sampling design is indicated in the \code{design} argument.
#' @param weights A character string indicating the name of the column with sampling weights. It could be \code{NULL} if the sampling design is indicated in the \code{design} argument.
#' @param design An object of class \code{survey.design} generated by \code{survey::svydesign()}. It could be \code{NULL} if information about \code{cluster}, \code{strata}, \code{weights} and \code{data} are given.
#' @param family A character string indicating the family to fit LASSO models. Choose between \code{gaussian} (to fit linear models) or \code{binomial} (for logistic models).
#' @param lambda.grid A numeric vector indicating a grid for penalization parameters. The default option is \code{lambda.grid = NULL}, which considers the default grid selected by the function \code{glmnet::glmnet()}.
#' @param method A character string indicating the method to be applied to define replicate weights. Choose between one of these: \code{JKn}, \code{dCV}, \code{bootstrap}, \code{subbootstrap}, \code{BRR}, \code{split}, \code{extrapolation}.
#' @param k A numeric value indicating the number of folds to be defined. Default is \code{k=10}. Only applies for the \code{dCV} method.
#' @param R A numeric value indicating the number of times the sample is partitioned. Default is \code{R=1}. Only applies for \code{dCV}, \code{split} or \code{extrapolation} methods.
#' @param B A numeric value indicating the number of bootstrap resamples. Default is \code{B=200}. Only applies for \code{bootstrap} and  \code{subbootstrap} methods.
#' @param dCV.sw.test A logical value indicating the method for estimating the error for \code{dCV} method. \code{FALSE}, (the default option) estimates the error for each test set and defines the cross-validated error based on the average strategy. Option \code{TRUE} estimates the cross-validated error based on the pooling strategy
#' @param train.prob A numeric value between 0 and 1, indicating the proportion of clusters (for the method \code{split}) or strata (for the method \code{extrapolation}) to be set in the training sets. Default is \code{train.prob = 0.7}. Only applies for \code{split} and \code{extrapolation} methods.
#' @param method.split A character string indicating the way in which replicate weights should be defined in the \code{split} method. Choose one of the following: \code{dCV}, \code{bootstrap} or \code{subbootstrap}. Only applies for \code{split} method.
#' @param print.rw A logical value. If \code{TRUE}, the data set with the replicate weights is saved in the output object. Default \code{print.rw=FALSE}.
#'
#' @importFrom graphics abline mtext
#' @importFrom stats as.formula coef predict runif
#'
#' @return The output object of the function \code{wlasso()} is an object of class \code{wlasso}. This object is a list containing 4 or 5 elements, depending on the value set to the argument \code{print.rw}. Below we describe the contents of these elements:
#' - `lambda`: A list containing information of two elements:
#'   - `grid`: A numeric vector indicating all the values considered for the tuning parameter.
#'   - `min`: A numeric value indicating the value of the tuning parameter that minimizes the average error (i.e., selected optimal tuning parameter).
#' - `error`: A list containing information of two elements:
#'   - `average`: A numeric vector indicating the average error corresponding to each tuning parameter.
#'   - `all`: A numeric matrix indicating the error of each test set for each tuning parameter.
#' - `model`: A list containing information of two elements in relation to the fitted models. Note that all these models are fitted considering the whole data set (and not uniquely the training sets).
#'   - `grid`: A list with the information about the models fitted for each of the tuning parameters considered (i.e., all the values in the \code{lambda$grid} object):
#'     - `a0`: a numeric vector of model intercepts across the whole grid of tuning parameters (hence, of the same length as \code{lambda$grid}).
#'     - `beta`: a matrix of regression coefficients corresponding to all the considered covariates across the whole grid of tuning parameters (the number of rows is equal to the number of covariates considered and the number of columns to the length of \code{lambda$grid}).
#'     - `df`: a numeric vector of the degrees of freedom (i.e., the number of coefficients different from zero) across the whole grid of tuning parameters  (hence, of the same length as \code{lambda$grid}).
#'   - `min`: A list with the information about the model fitted considering uniquely the tuning parameter that minimizes the error in the training models (i.e., the optimal tuning parameter selected between the elements in \code{lambda$grid}):
#'     - `a0`: a numeric value indicating the intercept value of the selected model.
#'     - `beta`: a matrix of regression coefficients corresponding to all the considered covariates for the selected tuning parameters (the number of rows is equal to the number of covariates considered and the number of columns is one).
#'     - `df`: a numeric value indicating the degrees of freedom (i.e., the number of coefficients different from zero) of the selected model.
#' - `data.rw`: A data frame containing the original data set and the replicate weights added to define training and test sets. Only included in the output object if \code{print.rw=TRUE}.
#' - `call`: an object containing the information about the way in which the function has been run.
#' - `alpha`: When multiple values of alpha are supplied, a list containing two elements:
#'    - `grid`: A data.frame with values of alpha considered, the associated lambda minimizing the error, and the error
#'    - `min`: The value of alpha for which the error is minimized
#' @export
#'
#' @examples
#' data(simdata_lasso_binomial)
#' mcv <- wglmnet(data = simdata_lasso_binomial,
#'               col.y = "y", col.x = 1:50,
#'               alpha = 1,
#'               family = "binomial",
#'               cluster = "cluster", strata = "strata", weights = "weights",
#'               method = "dCV", k=10, R=20)
#'
#' # Or equivalently:
#' mydesign <- survey::svydesign(ids=~1, strata = ~strata, weights = ~weights,
#'                               nest = TRUE, data = simdata_lasso_binomial)
#' mcv <- wglmnet(col.y = "y", col.x = 1:50, design = mydesign,
#'               family = "binomial", alpha = 1,
#'               method = "dCV", k=10, R=20)


wglmnet <- function(data = NULL, col.y = NULL, col.x = NULL, alpha = 1,
                   cluster = NULL, strata = NULL, weights = NULL, design = NULL,
                   family = "binomial",
                   lambda.grid = NULL,
                   method = "dCV",
                   k = 10, R = 1, B = 200,
                   dCV.sw.test = FALSE,
                   train.prob = 0.7, method.split = c("dCV", "bootstrap", "subbootstrap"),
                   print.rw = FALSE){

  if (length(alpha) == 1) {
    out <- wglmnet::wlasso(
      data = data,
      col.y = col.y,
      col.x = col.x,
      alpha = alpha,
      cluster = cluster,
      strata = strata,
      weights = weights,
      design = design,
      family = family,
      lambda.grid = lambda.grid,
      method = method,
      k = k, R = R, B = B,
      dCV.sw.test = dCV.sw.test,
      train.prob = train.prob,
      method.split = method.split,
      print.rw = print.rw
    )
    out$alpha$grid <- alpha
    out$alpha$min  <- alpha
    return(out)
  } else {
    out <- list()
    for (a in seq_along(alpha)) {
      tmp <- wglmnet::wlasso(
        data = data,
        col.y = col.y,
        col.x = col.x,
        alpha = alpha[a],
        cluster = cluster,
        strata = strata,
        weights = weights,
        design = design,
        family = family,
        lambda.grid = lambda.grid,
        method = method,
        k = k, R = R, B = B,
        dCV.sw.test = dCV.sw.test,
        train.prob = train.prob,
        method.split = method.split,
        print.rw = print.rw
      )
      out[[a]] <- data.frame(
        alpha      = alpha[a],
        lambda.min = tmp$lambda$min,
        error      = tmp$error$average[which(tmp$lambda$grid == tmp$lambda$min)]
      )
    }
    out <- do.call(rbind, out)
    selected <- wglmnet::wlasso(
      data = data,
      col.y = col.y,
      col.x = col.x,
      alpha = out[which.min(out$error), "alpha"],
      cluster = cluster,
      strata = strata,
      weights = weights,
      design = design,
      family = family,
      lambda.grid = lambda.grid,
      method = method,
      k = k, R = R, B = B,
      dCV.sw.test = dCV.sw.test,
      train.prob = train.prob,
      method.split = method.split,
      print.rw = print.rw
    )
    selected$alpha$grid <- out
    selected$alpha$min  <- out[which.min(out$error), "alpha"]
    return(selected)
  }
}
